-- depends_on: {{ ref('silver__operations') }}
{{ config(
    materialized = 'incremental',
    unique_key = ["operations_id"],
    incremental_predicates = ["dynamic_range_predicate", "partition_id::date"],
    merge_exclude_columns = ["inserted_timestamp"],
    cluster_by = ['closed_at::DATE','partition_id','modified_timestamp::DATE'],
    tags = ['core']
) }}

SELECT 
    partition_id,
    op_id,
    account,
    amount,
    asset_code,
    asset_issuer,
    asset_type,
    asset_id,
    authorize,
    balance_id,
    buying_asset_code,
    buying_asset_issuer,
    buying_asset_type,
    buying_asset_id,
    "from",
    funder,
    high_threshold,
    home_domain,
    inflation_dest,
    "into",
    "limit",
    low_threshold,
    master_key_weight,
    med_threshold,
    name,
    offer_id,
    path,
    price,
    d,
    n,
    selling_asset_code,
    selling_asset_issuer,
    selling_asset_type,
    selling_asset_id,
    set_flags,
    set_flags_s,
    signer_key,
    signer_weight,
    source_amount,
    source_asset_code,
    source_asset_issuer,
    source_asset_type,
    source_asset_id,
    source_max,
    starting_balance,
    "to",
    trustee,
    trustor,
    trustline_asset,
    "value",
    clear_flags,
    clear_flags_s,
    destination_min,
    bump_to,
    sponsor,
    sponsored_id,
    begin_sponsor,
    authorize_to_maintain_liabilities,
    clawback_enabled,
    liquidity_pool_id,
    reserve_a_asset_type,
    reserve_a_asset_id,
    reserve_a_asset_code,
    reserve_a_asset_issuer,
    reserve_a_max_amount,
    reserve_a_deposit_amount,
    reserve_b_asset_type,
    reserve_b_asset_id,
    reserve_b_asset_code,
    reserve_b_asset_issuer,
    reserve_b_max_amount,
    reserve_b_deposit_amount,
    min_price,
    min_price_r,
    max_price,
    max_price_r,
    shares_received,
    reserve_a_min_amount,
    reserve_b_min_amount,
    shares,
    reserve_a_withdraw_amount,
    reserve_b_withdraw_amount,
    op_source_account,
    op_source_account_muxed,
    transaction_id,
    type,
    transaction_hash,
    ledger_sequence,
    txn_account,
    account_sequence,
    max_fee,
    txn_operation_count,
    txn_created_at,
    memo_type,
    memo,
    time_bounds,
    successful,
    fee_charged,
    fee_account,
    new_max_fee,
    account_muxed,
    fee_account_muxed,
    ledger_hash,
    previous_ledger_hash,
    transaction_count,
    ledger_operation_count,
    closed_at,
    total_coins,
    fee_pool,
    base_fee,
    base_reserve,
    max_tx_set_size,
    protocol_version,
    successful_transaction_count,
    failed_transaction_count,
    batch_id,
    batch_run_date,
    batch_insert_ts,
    ledger_bounds,
    min_account_sequence,
    min_account_sequence_age,
    min_account_sequence_ledger_gap,
    extra_signers,
    asset_balance_changes,
    parameters,
    parameters_decoded,
    function,
    address,
    soroban_operation_type,
    extend_to,
    contract_id,
    contract_code_hash,
    resource_fee,
    soroban_resources_instructions,
    soroban_resources_read_bytes,
    soroban_resources_write_bytes,
    transaction_result_code,
    inclusion_fee_bid,
    inclusion_fee_charged,
    resource_fee_refund,
    operation_result_code,
    operation_trace_code,
    op_application_order,
    txn_application_order,
    _inserted_timestamp,
    {{ dbt_utils.generate_surrogate_key(['op_id']) }} AS operations_id,
    SYSDATE() AS inserted_timestamp,
    SYSDATE() AS modified_timestamp,
    '{{ invocation_id }}' AS _invocation_id
FROM {{ ref('silver__operations') }}

{% if is_incremental() %}
WHERE
    modified_timestamp >= (
        SELECT
            MAX(modified_timestamp)
        FROM
            {{ this }}
    )
{% endif %}